#ajax_relogin:
#  path:     /login_check
#  defaults: { _controller: FOSUserBundle:Security:check }
#  requirements:
#    _method:  POST
#  options:
#    expose: true
#
#login_exposed:
#  path:     /login
#  defaults: { _controller: FOSUserBundle:Security:login }
#  requirements:
#    _method:  GET|POST
#  options:
#    expose: true