services:
#    rad.example:
#        class: Atompulse\Bundle\RadBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

  # Export routes to web
  rad.application.routing.export:
    class:  Atompulse\Bundle\RadBundle\Services\Routing\RoutesExportService
    calls:
      - [setContainer, ['@service_container']]
    tags:
      - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

  # JSON Request Data Resolver
  rad.application.request.json_post_data_resolver:
    class:  Atompulse\Bundle\RadBundle\Services\RequestData\JsonPostDataResolverService
    arguments: []
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 9999 }

  # XmlHttpRequest exception response handler
  rad.application.request.ajax_exception_handler:
    class:  Atompulse\Bundle\RadBundle\Services\Exception\AjaxExceptionHandlerService
    arguments: []
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 250 }
